passive: crafter size12m crafter-passive
passive-full-ortho: crafter size12m crafter-passive full-ortho
aggressive: crafter size12m crafter-aggressive
aggressive-full-ortho: crafter size12m crafter-aggressive full-ortho
weak: crafter size12m crafter-weak
all: crafter size50m crafter-all
test: crafter debug